FROM alpine

LABEL maintainer="Marc Partensky <marc.partensky@gmail.com"
ENV DEBIAN_FRONTEND=noninteractive

COPY nvim /root/.config/nvim
COPY coc /root/.config/coc

RUN apk update
RUN apk add --no-cache git locales curl wget nodejs npm go make python3-dev py3-pip
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
RUN npm i -g yarn
RUN pip3 install --user neovim
# RUN rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
RUN tar xzvf nvim-linux64.tar.gz
RUN mv nvim-linux64/bin/nvim /usr/local/bin/nvim
RUN mv nvim-linux64/share/* /usr/local/share
RUN mv nvim-linux64/lib/* /usr/local/lib
RUN chmod +x /usr/local/bin/nvim
RUN rm -d nvim-linux64/* nvim-linux64

WORKDIR /root
RUN touch .vimrc
RUN nvim \
	+"source /root/.config/nvim/vim-plug/plugins.vim" \
	+CocInstall \
	+PlugUpdate \
	+UpdateRemotePlugins \
	+qall

ENTRYPOINT nvim
